name: biliran_alert
description: "BiliranAlert — A disaster management app to receive alerts, report incidents, and locate evacuation centers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  google_maps_flutter: ^2.6.1
  geolocator: ^13.0.1
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  animations: ^2.0.11
  url_launcher: ^6.3.1
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/animations/
    

