// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DreG6VqsYf30fWaT2wV-dzXlSaLRLcQ',
    appId: '1:778049583253:web:645967bbe4bab5e4cf439c',
    messagingSenderId: '778049583253',
    projectId: 'biliranalert',
    authDomain: 'biliranalert.firebaseapp.com',
    storageBucket: 'biliranalert.firebasestorage.app',
    measurementId: 'G-5EHCGE141P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUfTC-FabJDyYOHcUo_8R2FpnAs5p6WmQ',
    appId: '1:778049583253:android:ff833717bf8b581acf439c',
    messagingSenderId: '778049583253',
    projectId: 'biliranalert',
    storageBucket: 'biliranalert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYIXoCw1iMybE4E1EU7w_GxVmlGHSlbk',
    appId: '1:778049583253:ios:5de97f3d3e42868ccf439c',
    messagingSenderId: '778049583253',
    projectId: 'biliranalert',
    storageBucket: 'biliranalert.firebasestorage.app',
    iosBundleId: 'com.example.biliranAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYIXoCw1iMybE4E1EU7w_GxVmlGHSlbk',
    appId: '1:778049583253:ios:5de97f3d3e42868ccf439c',
    messagingSenderId: '778049583253',
    projectId: 'biliranalert',
    storageBucket: 'biliranalert.firebasestorage.app',
    iosBundleId: 'com.example.biliranAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0DreG6VqsYf30fWaT2wV-dzXlSaLRLcQ',
    appId: '1:778049583253:web:1cae06ceda10d2d0cf439c',
    messagingSenderId: '778049583253',
    projectId: 'biliranalert',
    authDomain: 'biliranalert.firebaseapp.com',
    storageBucket: 'biliranalert.firebasestorage.app',
    measurementId: 'G-303REKBHPJ',
  );

}